using System.Text;
using Tusk.Application.Scaffolding;

namespace Tusk.Infrastructure.Scaffolding;

public class PublicIndexScaffolder : IPublicIndexScaffolder
{
    public void EnsureDefaultPublicIndex(string cwd)
    {
        try
        {
            string publicDir = Path.Combine(cwd, "public");
            string indexPath = Path.Combine(publicDir, "index.php");

            if (File.Exists(indexPath))
            {
                return;
            }

            Directory.CreateDirectory(publicDir);

            var sb = new StringBuilder();
            sb.AppendLine("<?php");
            sb.AppendLine("/**");
            sb.AppendLine(" * Default front controller generated by Tusk.");
            sb.AppendLine(" *");
            sb.AppendLine(" * This file was created by `tusk init`.");
            sb.AppendLine(" */");
            sb.AppendLine();
            sb.AppendLine("declare(strict_types=1);");
            sb.AppendLine();
            sb.AppendLine("// Try to load Composer's autoloader if it exists");
            sb.AppendLine("@include __DIR__ . '/../vendor/autoload.php';");
            sb.AppendLine();
            sb.AppendLine("echo \"Hello from Tusk!\\n\";");

            File.WriteAllText(indexPath, sb.ToString());
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[tusk] Failed to create public/index.php: {ex.Message}");
        }
    }
}
