using System.Text;
using Ivory.Application.Scaffolding;

namespace Ivory.Infrastructure.Scaffolding;

public class PublicIndexScaffolder : IPublicIndexScaffolder
{
    public void EnsureDefaultPublicIndex(string cwd)
    {
        string publicDir = Path.Combine(cwd, "public");
        string indexPath = Path.Combine(publicDir, "index.php");

        if (File.Exists(indexPath))
        {
            return;
        }

        Directory.CreateDirectory(publicDir);

        var sb = new StringBuilder();
        sb.AppendLine("<?php");
        sb.AppendLine("/**");
        sb.AppendLine(" * Default front controller generated by Ivory.");
        sb.AppendLine(" *");
        sb.AppendLine(" * This file was created by `ivory init`.");
        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine("declare(strict_types=1);");
        sb.AppendLine();
        sb.AppendLine("// Try to load Composer's autoloader if it exists");
        sb.AppendLine("@include __DIR__ . '/../vendor/autoload.php';");
        sb.AppendLine();
        sb.AppendLine("echo \"Hello from Ivory!\\n\";");

        File.WriteAllText(indexPath, sb.ToString());
    }
}

